services:
  # FastAPI application
  api:
    build: . # build image from Dockerfile in this directory
    env_file:
      - .env
    ports: 
      - "8000:8000" # map poet 8000 on machine to port 8000 in container
    volumes:
      - .:/app # mount curr dir into /app for live-reloading
    depends_on:
      - db # wait for db service to be healthy before starting

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432" # expose postgres port (for debugging)
    volumes:
      - postgres_data:/var/lib/postgresql/data # persist database data
      - ./init-db:/docker-entrypoint-initdb.d # mount init folder 
    healthcheck:
      # test if Postgres is ready to accept connections
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # Dashboard service
  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./dashboard:/app
  
volumes:
  postgres_data:
